### ISSUE TITLE
ngx-typeahead - how to change API instead of goggle suggestion

### ISSUE THREAD

**Issue by arunyadav13** [orizens/ngx-typeahead#1]
This is working fine with http://suggestqueries.google.com/complete/search but not working if I am using another custom API instead of google suggestion.

May I get some another example with different API.

**Comment by iamkallolpratim** [comment]
facing the same problem, Please suggest me @orizens

**Comment by sameerargadeuh** [comment]
I guess the ngx-typeahead is useful for situations where you want to use cross origin url,
for same origin ones you need to use tyepahead from ngx-bootstrap.

**Comment by orizens** [comment]
hi all.
ngx-typeahead is using "jsonp" rather than http.
i'll look into integrating an "http" - this should be easy.

**Comment by orizens** [comment]
https://github.com/orizens/ngx-typeahead/commit/445c7e13c104d4d4fc3688c69e8c3fc82aff6126  added support for choosing "http" protocol as well a s request method (get, put, post etc...)
