### ISSUE TITLE
Always first element is selected when selecting with a mouse click

### ISSUE THREAD

**Issue by marcoziliotto** [orizens/ngx-typeahead#27]
Hi @orizens, 
I found out that always the first element gets selected when clicking, but everything works well if element is selected through keyboard.
You can find here an example of the problem: https://stackblitz.com/edit/angular-2msrqa

It seems that only happens with version 6.0.2 and angular 6.1.0

Thank you
Marco

**Comment by justin-nodeboy** [comment]
+ 1

**Comment by marcoziliotto** [comment]
Thank you @orizens!
