### ISSUE TITLE
How to display custom array of objects?

### ISSUE THREAD

**Issue by rahulkr7010** [orizens/ngx-typeahead#29]
I created an angular project in 6 and I am using rective form. My HTML looks like as below

```
<div class="col-md-6">
      <div class="user-input-wrp ">
           <input type="text" class="inputText input-icon sign-po" placeholder=" " formControlName="postoffice" ngxTypeahead  [taList]="postalCodes">
             <span class="floating-label sign-left0">Post Office</span>
        </div>
</div>
```

And my .ts file has 

` public postalCodes: Array<any> = [{id: 1, code: '686501'}, {id: 2, code: '686502'}, {id: 3, code: '686503'}, `{id: 4, code: '686504'}];

But when typing it loads as [object] [object]. I want to show codes while typing.

**Comment by sharmaparas** [comment]
<div class="col-md-6">
      <div class="user-input-wrp ">
           <input type="text" class="inputText input-icon sign-po" placeholder=" " formControlName="postoffice" ngxTypeahead  [taList]="postalCodes" [taItemTpl]="itemTpl">
             <span class="floating-label sign-left0">Post Office</span>
        </div>
</div>

<ng-template #itemTpl let-result>
  {{ result.result.code}}
</ng-template>
