### ISSUE TITLE
How to use static array list instead of  [taUrl] ?

### ISSUE THREAD

**Issue by balaganapathynt** [orizens/ngx-typeahead#3]
For Eg:
I would like to give input as static array
  public url2 = [
  "Clementina DuBuque",
  "Ervin Howell",
  "halisi",
  "Nicholas Runolfsdottir V",
  "Taylor",
  "Kim"
];
instead of URL
 public url2 = "data.json";

**Comment by orizens** [comment]
hi @balaganapathynt 
this component is designed to work with an async request.
I will consider adding support for a static list.

**Comment by orizens** [comment]
hi @balaganapathynt 
version 0.1.0 now supports Angular 5 and a static list.
