### ISSUE TITLE
Error in JSONP

### ISSUE THREAD

**Issue by bbj1980** [orizens/ngx-typeahead#4]
Getting Error
This is my Input
```  
<input type="text" [value]="query"
                                        ngxTypeahead
                                        [taUrl]="searchurl"
                                        [taParams]="{}"
                                        (taSelected)="handleResultSelected($event)"
                                        
                                
                              >
```
I am getting proper response from Rest get service, but it returning me following error

something went wrong !Response with status: 200 Ok for URL: http://10.4.3.14/ICEMaster/ICEMaster.svc/GetOccupation?callback=__ng_jsonp__.__req0.finished&q=aaa

Response of occupation service is attached.

**Comment by orizens** [comment]
can you share a plunkr?

**Comment by orizens** [comment]
closing this issue - as there's no response.
