### ISSUE TITLE
ngx-typeahead not compatible with Angular 5.0.0

### ISSUE THREAD

**Issue by goatcube** [orizens/ngx-typeahead#5]
Due to this change - https://github.com/angular/angular/commit/7522987, ngOutletContext must be changed to ngTemplateOutletContext.

Error with Angular 5:

Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ng-template
        [ngTemplateOutlet]="taItemTpl" 
        [ERROR ->][ngOutletContext]="{ $implicit: {result: result, index: i} }"
      ></ng-template>
    </button>
"): ng:///NgxTypeaheadModule/NgxTypeAheadComponent.html@11:8
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("ion(result)">
      <span *ngIf="!taItemTpl"><i class="fa fa-search"></i> {{ result }}</span>
      [ERROR ->]<ng-template
        [ngTemplateOutlet]="taItemTpl" 
        [ngOutletContext]="{ $implicit: {result:"): ng:///NgxTypeaheadModule/NgxTypeAheadComponent.html@9:6
    at syntaxError (compiler.js?dd9e:466)
    at TemplateParser.parse (compiler.js?dd9e:24312)
    at JitCompiler._parseTemplate (compiler.js?dd9e:33699)
    at JitCompiler._compileTemplate (compiler.js?dd9e:33674)
    at eval (compiler.js?dd9e:33576)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js?dd9e:33576)
    at eval (compiler.js?dd9e:33446)
    at Object.then (compiler.js?dd9e:455)
    at JitCompiler._compileModuleAndComponents (compiler.js?dd9e:33445)

**Comment by gdinant** [comment]
`ngOutletContext` was deprecated and replaced by `ngTemplateOutletContext`

**Comment by orizens** [comment]
@gdinant  thanks for the pr.
there are further changed to be made: updating the [starter and dependencies](https://github.com/robisim74/angular-library-starter/blob/master/CHANGELOG.md) so the 0.4 version will be released only after.

**Comment by IAMtheIAM** [comment]
Please release this as 0.0.3.1 hotfix. we need this to work in angular 5

**Comment by orizens** [comment]
hi @IAMtheIAM v 0.04 released. 
Please confirm it is working with Angular 5.
thanks.

**Comment by orizens** [comment]
hi @gdinant , @IAMtheIAM 
please try **beta** version ```npm i ngx-typeahead@0.0.43``` and let me know if that works out, so i can release it as v 0.0.5

**Comment by orizens** [comment]
hi. 
version 0.1.0 released and supports Angular 5.
